[project]
name = "film-bot"
version = "0.1.0"
description = "Telegram bot for selecting anime and doramas"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests==2.32.3",
    "pydantic-settings==2.9.1",
]

[tool.ruff.lint]
select = ["ALL"]
